# Stages
# Stage-1:
  # Task-1: Build Docker Image and push to Azure Container Registry ACR
  # Task-2: Copy kube-manifest files to Build Artifact Directory
  # Task-3: Publish build articats to Azure Pipelines
# Pipeline Hierarchial Flow: Stages -> Stage -> Jobs -> Job -> Steps -> Task1, Task2, Task3  

trigger:
- main

pool:
  name: default

stages:
  - stage: Build
    displayName: Build Stage
    jobs:
    - job: Build
      displayName: Build Job for Docker
      steps:
      - task: Docker@2
        inputs:
          containerRegistry: 'acrazure1989'
          repository: 'custumapp'
          command: 'buildAndPush'
          Dockerfile: '**/Dockerfile'